### ISSUE TITLE
Project is Ready for Checkpoint 1 Review

### ISSUE THREAD

**Issue by ChampaineV** [ChampaineV/indieProject#1]
@pawaitemadisoncollege - checkpoint 1 is ready for review

**Comment by pawaitemadisoncollege** [comment]
@ChampaineV You have a good start on your indie project!!! Many of your deliverables for checkpoint 1 do a thorough job explaining the direction of your project and it's clear you've put some thought into this already. It sounds like a very useful application!

See below for my comments and questions.

**Problem statement**

The problem statement clearly explains what the solution will provide. 
- [x] The statement does not seem to clearly define what problem this solves. Is there a bit more information that you can add to explain the problems with productivity that students might currently experience that this application will solve? 

**Project Technologies/Techniques**

- [x]  For Authentication, we'll be using Amazon's Cognito.
- [x]  It would be helpful to include the versions of the tools and libraries that you are using (you may not know all of these yet, but be sure to add them when you do decide). This way, a prospective employer can see that you are using current tech.

**Screen Designs**

- [x] Are all MVP user stories covered by the screens? It seems that some may be missing.

**Project Plan**

- [x] The link to in the readme to the plan appears to need a formatting fix, as it shows up like this:  ![Screen Shot 2022-09-22 at 6 25 32 PM](https://user-images.githubusercontent.com/13874466/191868317-0cc57afe-9e1f-4d96-b10a-4f309581faf3.png)
 - [x] The project plan appears to be missing weekly detail. Sometimes it can be hard to know where to start with this planning. You might consider listing specific user stories in the plan and include when you will start each story and when you are targeting finishing it.
- [x]  It may helpful to break down the individual stories into tasks and list those in the plan or put them into a tool like Trello. 

**User Stories**

The scope here looks doable in a semester and covers almost all of the key objectives for the ent java project.

- [x] Is there a user story that covers deleting? If not, is there something meaningful that you could add to cover this indie project objective?

**Time Log**

- [x] Looks to be complete, with regular weekly entries.
- [x] It may be useful to include the amount of time spent on the various tasks - this can help us identify areas that are working well and areas for improvement.  

**Other**

- [x] There is a link to tasks.md, but the document is empty. Maybe this is not needed?

**Comment by ChampaineV** [comment]
@pawaitemadisoncollege I've made updates to Checkpoint 1

**Comment by pawaitemadisoncollege** [comment]
Your updates took this work to the next level!

- [x] Is this needed if you are using cognito for authentication? https://github.com/ChampaineV/indieProject/blob/35fd43c714a18e54271f46d5a83bea521c6be1b7/src/main/java/edu/productivity/entity/User.java#L30-L31
